this.LINK_INVALID_TYPE = "MSG_LINK_INVALID_TYPE";
this.LINK_URL_EMPTY = "MSG_LINK_URL_EMPTY";
this.LINK_TARGET_OBJECT_TYPE_CODE_EMPTY = "MSG_LINK_TARGET_OBJECT_TYPE_CODE_EMPTY";
this.LINK_TARGET_OBJECT_ID_EMPTY = "MSG_LINK_TARGET_OBJECT_ID_EMPTY";