 this.AUTH_MISSING_REWARD_CREATE = "MSG_AUTH_MISSING_REWARD_CREATE";
 this.AUTH_MISSING_REWARD_READ = "MSG_AUTH_MISSING_REWARD_READ";
 this.AUTH_MISSING_REWARD_DELETE = "MSG_AUTH_MISSING_REWARD_DELETE";
 this.AUTH_MISSING_REWARD_UPDATE = "MSG_AUTH_MISSING_REWARD_UPDATE";
 this.AUTH_MISSING_REWARD_STATUS_TRANS = "MSG_AUTH_MISSING_REWARD_STATUS_TRANS";
 
 this.REWARD_UNCHANGEABLE = "MSG_REWARD_UNCHANGEABLE";
 this.REWARD_IDEA_MISSING = "MSG_REWARD_IDEA_MISSING";
 this.REWARD_IDEA_CONTRIBUTION_SHARE_MISSING = "MSG_REWARD_IDEA_CONTRIBUTION_SHARE_MISSING";
 this.REWARD_ITEM_MISSING = "MSG_REWARD_ITEM_MISSING";
 this.REWARD_INVALID_STATUS_TRANSITION = "MSG_REWARD_INVALID_STATUS_TRANSITION";
 this.REWARD_NO_STATUS_TRANSITIONS = "MSG_REWARD_NO_STATUS_TRANSITIONS";
 this.REWARD_BULK_DELETE_PARAMETER_REQUIRED = "MSG_REWARD_BULK_DELETE_PARAMETER_REQUIRED";
 this.REWARD_DOWNLOAD_PARAMETER_REQUIRED = "MSG_REWARD_DOWNLOAD_PARAMETER_REQUIRED";
 this.REWARDS_DELETE_FAILURE = "MSG_REWARDS_DELETE_FAILURE";
 this.REWARD_DUPLICATE = "MSG_REWARD_DUPLICATE";
 
 this.SYSTEM_REWARD_UNACTIVE = "MSG_SYSTEM_REWARD_UNACTIVE";
 
 this.IDEA_REWARD_BULK_DELETE_PARAMETER_REQUIRED = "MSG_IDEA_REWARD_BULK_DELETE_PARAMETER_REQUIRED";
 this.IDEA_REWARD_BULK_CHANGE_AUTHOR_PARAMETER_REQUIRED = "MSG_IDEA_REWARD_BULK_CHANGE_AUTHOR_PARAMETER_REQUIRED";