this.AUTH_MISSING_COMMENT_CREATE = "MSG_AUTH_MISSING_COMMENT_CREATE";
this.AUTH_MISSING_COMMENT_UPDATE = "MSG_AUTH_MISSING_COMMENT_UPDATE";
this.AUTH_MISSING_COMMENT_DELETE = "MSG_AUTH_MISSING_COMMENT_DELETE";
this.AUTH_MISSING_COMMENT_READ = "MSG_AUTH_MISSING_COMMENT_READ";

this.AUTH_MISSING_IDEA_DELETE = "MSG_AUTH_MISSING_IDEA_DELETE";
this.AUTH_MISSING_IDEA_UPDATE = "MSG_AUTH_MISSING_IDEA_UPDATE";
this.AUTH_MISSING_IDEA_READ = "MSG_AUTH_MISSING_IDEA_READ";
this.AUTH_MISSING_IDEA_COACH = "MSG_AUTH_MISSING_IDEA_COACH";
this.AUTH_MISSING_IDEA_COACH_UNASSIGN = "MSG_AUTH_MISSING_IDEA_COACH_UNASSIGN";
this.AUTH_MISSING_IDEA_COACH_ASSIGN = "MSG_AUTH_MISSING_IDEA_COACH_ASSIGN";
this.AUTH_MISSING_IDEA_SUBMIT = "MSG_AUTH_MISSING_IDEA_SUBMIT";
this.AUTH_MISSING_IDEA_STATUS_TRANSITION = "MSG_AUTH_MISSING_IDEA_STATUS_TRANSITION";
this.AUTH_MISSING_BACKOFFICE_ATTACHMENT = "MSG_AUTH_MISSING_BACKOFFICE_ATTACHMENT";
this.AUTH_MISSING_BACKOFFICE_WALL = "MSG_AUTH_MISSING_BACKOFFICE_WALL";
this.AUTH_MISSING_IDEA_EXPERT = "MSG_AUTH_MISSING_IDEA_EXPERT";
this.AUTH_MISSING_REASSIGN_IDEA = "MSG_AUTH_MISSING_REASSIGN_IDEA";
this.AUTH_MISSING_REASSIGN_IDEA_SUBMITTER = "MSG_AUTH_MISSING_REASSIGN_IDEA_SUBMITTER";
this.AUTH_MISSING_CAMPAIGN_READ = "MSG_AUTH_MISSING_CAMPAIGN_READ";
this.AUTH_CAMP_MUST_NOT_BE_NULL = "MSG_AUTH_CAMP_MUST_NOT_BE_NULL";

this.ATTRIBUTE_NOT_CHANGEABLE = "MSG_ATTRIBUTE_NOT_CHANGEABLE";
this.IDEA_NOT_CHANGEABLE = "MSG_IDEA_NOT_CHANGEABLE";
this.IDEA_NOT_REPRODUCIABLE = "MSG_IDEA_NOT_REPRODUCIABLE";
this.ATTACHMENT_NOT_DELETEABLE = "MSG_IDEA_ATTACHMENT_NOT_DELETEABLE";
this.INTERNAL_ATTACHMENT_TITLE_IMAGE_NOT_ALLOWED = "MSG_IDEA_INTERNAL_ATTACHMENT_TITLE_IMAGE_NOT_ALLOWED";

this.CAMPAIGN_STATUS_DRAFT = "MSG_CAMPAIGN_STATUS_DRAFT";
this.IDEA_DELETE_STATUS_FAILED = "MSG_IDEA_DELETE_STATUS_FAILED";
this.CONTRIBUTOR_NOT_SUBMITTER = "MSG_CONTRIBUTOR_NOT_SUBMITTER";
this.ASSIGN_COACH_INVALID_COACH = "MSG_ASSIGN_COACH_INVALID_COACH";
this.ASSIGN_COACH_NO_COACH_AVAILABLE = "MSG_ASSIGN_COACH_NO_COACH_AVAILABLE";
this.ASSIGN_COACH_NO_COACH_ASSIGNED = "MSG_ASSIGN_COACH_NO_COACH_ASSIGNED";
this.ASSIGN_COACH_ALREADY_SET ="MSG_ASSIGN_COACH_ALREADY_SET";
this.EXPERT_NOT_SUBMITTER_OR_CONTRIBUTOR = "MSG_EXPERT_NOT_SUBMITTER_OR_CONTRIBUTOR";

this.IDEA_DESCRIPTION_MANDATORY = "MSG_IDEA_DESCRIPTION_MANDATORY";
this.IDEA_CAMPAIGN_MANDATORY = "MSG_IDEA_CAMPAIGN_MANDATORY";
this.IDEA_NO_FURTHER_SUBMIT = "MSG_IDEA_NO_FURTHER_SUBMIT";
this.IDEA_ONLY_ONE_COACH = "MSG_IDEA_ONLY_ONE_COACH"; 
this.CAMPAIGN_VALIDITY = "MSG_CAMPAIGN_VALIDITY";

this.IDEA_NO_MORE_STATUS_TRANSITION = "MSG_IDEA_NO_MORE_STATUS_TRANSITION";
this.IDEA_INVALID_STATUS_TRANSITION = "MSG_IDEA_INVALID_STATUS_TRANSITION";
this.IDEA_INVALID_ACTION_CODE_TRANSITION = "MSG_IDEA_INVALID_ACTION_CODE_TRANSITION";
this.IDEA_STATUS_TRANSITION_DECISION_MISSING = "MSG_IDEA_STATUS_TRANSITION_DECISION_MISSING";
this.IDEA_STATUS_TRANSITION_RESPONSE_MISSING = "MSG_IDEA_STATUS_TRANSITION_RESPONSE_MISSING";

this.IDEA_BULK_PHASE_CODE_PARAMETER_REQUIRED = "MSG_IDEA_BULK_PHASE_CODE_PARAMETER_REQUIRED";
this.IDEA_BULK_STATUS_MODEL_CODE_PARAMETER_REQUIRED = "MSG_IDEA_BULK_STATUS_MODEL_CODE_PARAMETER_REQUIRED";
this.IDEA_BULK_VOTE_DELETE_PARAMETER_REQUIRED = "MSG_IDEA_BULK_VOTE_DELETE_PARAMETER_REQUIRED";
this.IDEA_BULK_DELETE_RELATIONS_PARAMETER_REQUIRED = "MSG_IDEA_BULK_DELETE_RELATIONS_PARAMETER_REQUIRED"; 

this.COMMENT_IDEA_UNCHANGEABLE = "MSG_COMMENT_IDEA_UNCHANGEABLE";

this.AUTH_MISSING_VOTE_CREATE = "MSG_AUTH_MISSING_VOTE_CREATE";
this.AUTH_MISSING_VOTE_UPDATE = "MSG_AUTH_MISSING_VOTE_UPDATE";
this.AUTH_MISSING_VOTE_DELETE = "MSG_AUTH_MISSING_VOTE_DELETE";
this.AUTH_MISSING_VOTE_READ = "MSG_AUTH_MISSING_VOTE_READ";
this.DOUBLE_VOTE_ON_IDEA = "MSG_DOUBLE_VOTE_ON_IDEA";
this.DOUBLE_VOLUNTEER_ON_IDEA = "MSG_DOUBLE_VOLUNTEER_ON_IDEA";
this.VOTE_IDEA_DRAFT_VALIDITY = "MSG_VOTE_IDEA_DRAFT_VALIDITY";
this.VOTE_IDEA_DISCONTINUED = "MSG_VOTE_IDEA_DISCONTINUED";
this.VOTE_IDEA_MERGED = "MSG_VOTE_IDEA_MERGED";
this.VOTE_CAMPAIGN_PHASE_VALIDITY = "MSG_VOTE_CAMPAIGN_PHASE_VALIDITY";
this.VOTE_INVALID_VOTE_SCORE = "MSG_VOTE_INVALID_VOTE_SCORE";
this.VOTE_INVALID_STAR_VOTE = "MSG_VOTE_INVALID_STAR_VOTE";
this.VOTE_INVALID_LIKE_VOTE = "MSG_VOTE_INVALID_LIKE_VOTE";
this.VOTE_INVALID_LIKE_VOTE = "MSG_VOTE_INVALID_LIKE_VOTE";
this.VOTE_INVALID_DISLIKE_VOTE = "MSG_VOTE_INVALID_DISLIKE_VOTE";
this.VOTE_IDEA_UNCHANGEABLE = "MSG_VOTE_IDEA_UNCHANGEABLE";
this.VOTE_BULK_DELETE_PARAMETER_REQUIRED = "MSG_VOTE_BULK_DELETE_PARAMETER_REQUIRED";
this.VOTE_BULK_DELETE_TOO_MANY_PARAMETERS = "MSG_VOTE_BULK_DELETE_TOO_MANY_PARAMETERS";

this.AUTH_MISSING_IDEA_MERGE = "MSG_AUTH_MISSING_IDEA_MERGE";
this.IDEA_MERGE_NOT_ALLOWED_FOR_IDEA = "MSG_IDEA_MERGE_NOT_ALLOWED_FOR_IDEA";
this.IDEA_MERGE_PARAMETER_REQUIRED = "MSG_IDEA_MERGE_PARAMETER_REQUIRED";
this.IDEA_DUPLICATE_ALREADY_MARKED_AS_DUPLICATE = "MSG_IDEA_DUPLICATE_ALREADY_MARKED_AS_DUPLICATE";
this.IDEA_DUPLICATE_NOT_MARKED_AS_DUPLICATE = "MSG_IDEA_DUPLICATE_NOT_MARKED_AS_DUPLICATE";
this.IDEA_DUPLICATE_PARAMETER_REQUIRED = "MSG_IDEA_DUPLICATE_PARAMETER_REQUIRED";

this.IDEA_INVALID_CONTRIBUTION_SHARE = "MSG_IDEA_INVALID_CONTRIBUTION_SHARE";

this.FIELD_VALUE_INVALID_DATA = "MSG_FIELD_VALUE_INVALID_DATA";

this.INVALID_REWARD_DISMISS = "MSG_INVALID_REWARD_DISMISS";

this.ADD_EXPERT_INVALID_EXPERT = "MSG_ADD_EXPERT_INVALID_EXPERT";
this.ADD_EXPERT_NO_EXPERT_AVAILABLE = "MSG_ADD_EXPERT_NO_EXPERT_AVAILABLE";
this.ADD_EXPERT_NO_EXPERT_ASSIGNED = "MSG_ADD_EXPERT_NO_EXPERT_ASSIGNED";

this.ASSIGN_TAG_NO_TAG_AVAILABLE = "MSG_ASSIGN_TAG_NO_TAG_AVAILABLE";
this.ASSIGN_TAG_INVALID_TAG = "MSG_INVALID_EMPTY_TAG";
this.ASSIGN_TAG_NO_TAG_ASSIGNED = "MSG_ASSIGN_TAG_NO_TAG_ASSIGNED";
this.REASSIGN_CAMPAIGN_NOT_AVAILABLE = "MSG_REASSIGN_CAMPAIGN_NOT_AVAILABLE";
this.IDEA_SUBRESPONSIBILITY_LIST_DISABLED = "MSG_IDEA_SUBRESPONSIBILITY_LIST_DISABLED";
this.IDEA_EXISTS_EVALUATION_REQUEST = "MSG_IDEA_EXISTS_EVALUATION_REQUEST";

this.IDEA_BULK_CHANGE_AUTHOR_EXPERT = "MSG_IDEA_BULK_CHANGE_AUTHOR_EXPERT";
this.IDEA_BULK_CHANGE_AUTHOR_PARAMETER_REQUIRED = "MSG_IDEA_BULK_CHANGE_AUTHOR_PARAMETER_REQUIRED";
this.IDEA_BULK_CHANGE_AUTHOR_WRONG_AUTHOR_ID = "MSG_IDEA_BULK_CHANGE_AUTHOR_WRONG_AUTHOR_ID";
this.IDEA_BULK_CHANGE_AUTHOR_AUTHOR_ID_IS_NOT_PARTICIPANTS = "MSG_IDEA_BULK_CHANGE_AUTHOR_AUTHOR_ID_IS_NOT_PARTICIPANTS";
this.IDEA_BULK_CHANGE_AUTHOR_HAS_NO_AUTHORIZATION = "MSG_IDEA_BULK_CHANGE_AUTHOR_HAS_NO_AUTHORIZATION";
this.IDEA_BULK_CHANGE_AUTHOR_HAS_ANONYMOUS_IDEA = "MSG_IDEA_BULK_CHANGE_AUTHOR_HAS_ANONYMOUS_IDEA";

this.IDEA_NO_AUTHORIZATION_CHANGE_DECISION = "MSG_IDEA_NO_AUTHORIZATION_CHANGE_DECISION";
this.REASSIGN_CAMPAIGN_NOT_AVAILABLE_INTEGRATION_OBJECT = "MSG_REASSIGN_CAMPAIGN_NOT_AVAILABLE_INTEGRATION_OBJECT";

this.IDEA_SUBMIT_TRACKING_LOG_FAILED = "MSG_IDEA_SUBMIT_TRACKING_LOG_FAILED";

this.IDEA_SUBMIT_ANONYMOUS_FAILED = "MSG_IDEA_SUBMIT_ANONYMOUS_FAILED";

this.IDEA_LATEST_PARAMETER_REQUIRED = "MSG_IDEA_LATEST_PARAMETER_REQUIRED";
this.IDEA_LATEST_PARAMETER_TYPECODE_NOT_MATCH = "MSG_IDEA_LATEST_PARAMETER_TYPECODE_NOT_MATCH";

this.IDEA_MERGED_CANNOT_DELETE = "MSG_IDEA_MERGED_CANNOT_DELETE";

this.DESCRIPTION_CONTAINED_ILLEGAL_TAGS = "MSG_DESCRIPTION_CONTAINED_ILLEGAL_TAGS";