this.AUTH_MISSING_BLOG_UPDATE = "MSG_AUTH_MISSING_BLOG_UPDATE";
this.AUTH_MISSING_BLOG_READ = "MSG_AUTH_MISSING_BLOG_READ";
this.AUTH_MISSING_BLOG_CREATE = "MSG_AUTH_MISSING_BLOG_CREATE";
this.AUTH_MISSING_BLOG_DELETE = "MSG_AUTH_MISSING_BLOG_DELETE";
this.CHECK_AUTHOR_LENGTH = "MSG_CHECK_AUTHOR_LENGTH";