this.AUTH_MISSING_ATTACHMENT_CREATE = "MSG_AUTH_MISSING_ATTACHMENT_CREATE";
this.AUTH_MISSING_ATTACHMENT_UPDATE = "MSG_AUTH_MISSING_ATTACHMENT_UPDATE";
this.AUTH_MISSING_ATTACHMENT_DELETE = "MSG_AUTH_MISSING_ATTACHMENT_DELETE";
this.AUTH_MISSING_ATTACHMENT_READ= "MSG_AUTH_MISSING_ATTACHMENT_READ";

this.AUTH_MISSING_FOLDER_CREATE = "MSG_AUTH_MISSING_FOLDER_CREATE";
this.AUTH_MISSING_FOLDER_UPDATE = "MSG_AUTH_MISSING_FOLDER_UPDATE";
this.AUTH_MISSING_FOLDER_DELETE = "MSG_AUTH_MISSING_FOLDER_DELETE";
this.AUTH_MISSING_FOLDER_READ= "MSG_AUTH_MISSING_FOLDER_READ";

this.AUTH_MISSING_FOLDER_SHARE_CREATE = "MSG_AUTH_MISSING_FOLDER_SHARE_CREATE";
this.AUTH_MISSING_FOLDER_SHARE_UPDATE = "MSG_AUTH_MISSING_FOLDER_SHARE_UPDATE";
this.AUTH_MISSING_FOLDER_SHARE_DELETE = "MSG_AUTH_MISSING_FOLDER_SHARE_DELETE";
this.AUTH_MISSING_FOLDER_SHARE_READ= "MSG_AUTH_MISSING_FOLDER_SHARE_READ";

this.DUPLICATE_FOLDER_SHARE = "MSG_DUPLICATE_FOLDER_SHARE";

this.ATTACHMENT_DUPLICATE_ASSIGNMENT = "MSG_ATTACHMENT_DUPLICATE_ASSIGNMENT";
this.ATTACHMENT_DUPLICATE_ROLE_TYPE = "MSG_ATTACHMENT_DUPLICATE_ROLE_TYPE";
this.ATTACHMENT_INVALID_MEDIA_TYPE = "MSG_ATTACHMENT_INVALID_MEDIA_TYPE";
this.ATTACHMENT_INVALID_ROLE_TYPE = "MSG_ATTACHMENT_INVALID_ROLE_TYPE";
this.ATTACHMENT_FILE_EXT_NOT_ALLOWED = "MSG_ATTACHMENT_FILE_EXT_NOT_ALLOWED";
this.ATTACHMENT_EMPTY_DATA = "MSG_ATTACHMENT_EMPTY_DATA";
this.ATTACHMENT_EXCEED_MAX_SIZE = "MSG_ATTACHMENT_EXCEED_MAX_SIZE";
this.ATTACHMENT_VIDEO_NOT_ENABLED = "MSG_ATTACHMENT_VIDEO_NOT_ENABLED";
this.ATTACHMENT_FILE_MALICIOUS_CONTENT = "MSG_ATTACHMENT_FILE_MALICIOUS_CONTENT";
this.ATTACHMENT_FILE_MALICIOUS_SOFT = "MSG_ATTACHMENT_FILE_MALICIOUS_SOFT";
this.ATTACHMENT_BULK_CHANGE_AUTHOR_PARAMETER_REQUIRED = "MSG_ATTACHMENT_BULK_CHANGE_AUTHOR_PARAMETER_REQUIRED";
this.ATTACHMENT_FILE_MALWARESCANNING_SERVICE_UNAVAILABLE = "MSG_ATTACHMENT_FILE_MALWARESCANNING_SERVICE_UNAVAILABLE";
this.ATTACHMENT_FILE_MALWARESCANNING_SERVICE_ERROR = "MSG_ATTACHMENT_FILE_MALWARESCANNING_SERVICE_ERROR";

