this.AUTH_MISSING_NOTIFICATION_READ = "MSG_AUTH_MISSING_NOTIFICATION_READ";
this.AUTH_MISSING_NOTIFICATION_UPDATE = "MSG_AUTH_MISSING_NOTIFICATION_UPDATE";

this.MAIL_TEMPLATE_DUPLICATE_CODE = "MSG_UNIT_DUPLICATE_CODE";
this.MAIL_TEMPLATE_UNCHANGEABLE = "MSG_MAIL_TEMPLATE_UNCHANGEABLE";
this.MAIL_TEMPLATE_NO_COPY = "MSG_MAIL_TEMPLATE_NO_COPY";