this.FORMFIELD_VALUE_OPTION_LIST_INVALID = "MSG_FORMFIELD_VALUE_OPTION_LIST_INVALID";
this.IDEAFORM_UPDATE_NOT_EMPTY = "MSG_IDEAFORM_UPDATE_NOT_EMPTY";
this.FORM_DUPLICATE_CODE = "MSG_FORM_DUPLICATE_CODE";
this.FORM_UNDELETEABLE = "MSG_FORM_UNDELETEABLE";
this.FORM_PLAIN_CODE_UNCHANGABLE = "MSG_FORM_PLAIN_CODE_UNCHANGABLE";
this.FORM_FIELD_UNCHANGEABLE = "MSG_FORM_FIELD_UNCHANGEABLE";
this.ADMIN_ONLY_UNCHANGEABLE = "MSG_ADMIN_ONLY_UNCHANGEABLE";
this.FORM_FIELD_MANDATORY_UNCHANGEABLE = "MSG_FORM_FIELD_MANDATORY_UNCHANGEABLE";

this.FIELD_INVALID_CODE = "MSG_FIELD_INVALID_CODE";
this.FIELD_NUM_VALUE_INTERVAL_INVALID = "MSG_FIELD_NUM_VALUE_INTERVAL_INVALID";
this.FIELD_NUM_VALUE_STEP_SIZE_NEGATIVE = "MSG_FIELD_NUM_VALUE_STEP_SIZE_NEGATIVE";
this.FIELD_NUM_VALUE_STEP_SIZE_INVALID = "MSG_FIELD_NUM_VALUE_STEP_SIZE_INVALID";
this.FIELD_VALUE_OPTION_LIST_WRONG_DATATYPE = "MSG_FIELD_VALUE_OPTION_LIST_WRONG_DATATYPE";
this.FORMFIELD_DISPLAY_TEXT_EMPTY = "MSG_FIELD_DISPLAY_TEXT_EMPTY";