this.AUTH_MISSING_USER_SETTINGS_READ = "MSG_AUTH_MISSING_USER_SETTINGS_READ";
this.AUTH_MISSING_USER_SETTINGS_UPDATE = "MSG_AUTH_MISSING_USER_SETTINGS_UPDATE";
this.PRINCIPAL_IDENTITY_UNKNOWN = "MSG_PRINCIPAL_IDENTITY_UNKNOWN";
this.IDENTITY_NAME_UNKNWON = "MSG_IDENTITY_USER_NAME_UNKNOWN";
this.IDENTITY_NAME_UNIQUE = "MSG_IDENTITY_NAME_UNIQUE";
this.IDENTITY_CREATE_USER_FAIL = "MSG_IDENTITY_CREATE_USER_FAIL";
this.IDENTITY_USER_NAME_UNIQUE = "MSG_IDENTITY_USER_NAME_UNIQUE";
this.IDENTITY_FIRST_NAME_REQUIRE = "MSG_IDENTITY_FIRST_NAME_REQUIRE";
this.IDENTITY_LAST_NAME_REQUIRE = "MSG_IDENTITY_LAST_NAME_REQUIRE";
this.IDENTITY_USER_NAME_REQUIRE = "MSG_IDENTITY_USER_NAME_REQUIRE";
this.IDENTITY_USER_NAME_ILLEGAL = "MSG_IDENTITY_USER_NAME_ILLEGAL";
this.IDENTITY_GROUP_NAME_UNIQUE = "MSG_IDENTITY_GROUP_NAME_UNIQUE";
this.IDENTITY_DUPLICATE_GROUP_ASSIGNMENT = "MSG_IDENTITY_DUPLICATE_GROUP_ASSIGNMENT";
this.IDENTITY_DUPLICATE_USER_ASSIGNMENT = "MSG_IDENTITY_DUPLICATE_USER_ASSIGNMENT";
this.IDENTITY_DUPLICATE_IDENTITY_ASSIGNMENT = "MSG_IDENTITY_DUPLICATE_IDENTITY_ASSIGNMENT";
this.IDENTITY_NOT_CHANGEABLE = "MSG_IDENTITY_NOT_CHANGEABLE";

this.INVALID_IDENTITY = "MSG_INVALID_IDENTITY";
this.DUPLICATE_IDENTITY = "MSG_DUPLICATE_IDENTITY";

this.STATIC_ROLE_DOES_NOT_EXIST = "MSG_STATIC_ROLE_DOES_NOT_EXIST";
this.STATIC_ROLE_MISSING_AUTH = "MSG_STATIC_ROLE_MISSING_AUTH";

this.GROUP_IN_USE_DELETE_NOT_POSSIBLE = "MSG_GROUP_IN_USE_DELETE_NOT_POSSIBLE";
this.GROUP_MEMBER_RECURSION = "MSG_GROUP_MEMBER_RECURSION";

this.USER_NOT_FOUND = "MSG_USER_NOT_FOUND";
this.USER_DEACTIVATED = "MSG_USER_DEACTIVATED";
this.USER_DELETE_FAIL = 'MSG_USER_DELETED_FAIL';

this.LOCALE_INVALID = "MSG_LANGUAGE_LOCALE_INVALID";
this.MSG_GENERIC_AUTH_ERROR = "MSG_GENERIC_AUTH_ERROR";
this.IDENTITY_USER_CREATE_SUCCESS = "MSG_IDENTITY_USER_CREATE_SUCCESS";
this.IDENTITY_USER_CREATE_MAIL_SEND_FAIL = "MSG_IDENTITY_USER_CREATE_MAIL_SEND_FAIL";
this.IDENTITY_USER_CREATE_MAIL_SEND_SUCCESS = "MSG_IDENTITY_USER_CREATE_MAIL_SEND_SUCCESS";

this.QUICK_LINK_OBJECT_NOT_FOUND = "MSG_OBJECT_NOT_FOUND";
this.QUICK_LINK_STANDARD_NOT_ALLOW_TO_DELETE = "MSG_QUICK_LINK_STANDARD_NOT_ALLOW_TO_DELETE";
this.QUICK_LINK_STANDARD_ITEM_EXISTED = "MSG_QUICK_LINK_STANDARD_ITEM_EXISTED";
this.QUICK_LINK_URL_MAX_LENGTH_VIOLATED = "MSG_QUICK_LINK_URL_MAX_LENGTH_VIOLATED";
