this.AUTH_MISSING_CAMPAIGN_CREATE = "MSG_AUTH_MISSING_CAMPAIGN_CREATE";
this.AUTH_MISSING_CAMPAIGN_UPDATE = "MSG_AUTH_MISSING_CAMPAIGN_UPDATE";
this.AUTH_MISSING_CAMPAIGN_DELETE = "MSG_AUTH_MISSING_CAMPAIGN_DELETE";
this.AUTH_MISSING_CAMPAIGN_READ = "MSG_AUTH_MISSING_CAMPAIGN_READ";
this.AUTH_MISSING_CAMPAIGN_SUBMIT = "MSG_AUTH_MISSING_CAMPAIGN_SUBMIT";
this.AUTH_MISSING_CAMPAIGN_SUBMIT_UPDATE = "AUTH_MISSING_CAMPAIGN_SUBMIT_UPDATE";
this.AUTH_MISSING_BACKOFFICE_PRIVILEGES = "AUTH_MISSING_BACKOFFICE_PRIVILEGES";
this.AUTH_MISSING_CAMPAIGN_REGISTER = "MSG_AUTH_MISSING_CAMPAIGN_REGISTER"; 
this.AUTH_MISSING_REGISTER_PRIVILEGES = "MSG_AUTH_MISSING_REGISTER_PRIVILLEGE";

this.CAMPAIGN_DEFAULT_LANGUAGE_MANDATORY = "MSG_CAMPAIGN_DEFAULT_LANGUAGE_MANDATORY";
this.CAMPAIGN_LANGUAGE_INCOMPLETE_TITLE = "MSG_CAMPAIGN_LANGUAGE_INCOMPLETE_TITLE";
this.CAMPAIGN_LANGUAGE_INCOMPLETE_SHORT_TITLE = "MSG_CAMPAIGN_LANGUAGE_INCOMPLETE_SHORT_TITLE";

this.CAMPAIGN_IMAGE_MANDATORY = "MSG_CAMPAIGN_IMAGE_MANDATORY";

this.CAMPAIGN_ONE_CAMPAIGN_MANAGER_RECOMMENDED = "MSG_CAMPAIGN_ONE_CAMPAIGN_MANAGER_RECOMMENDED";
this.CAMPAIGN_ONE_COACH_RECOMMENDED = "MSG_CAMPAIGN_ONE_COACH_RECOMMENDED";
this.CAMPAIGN_ONE_EXPERT_RECOMMENDED = "MSG_CAMPAIGN_ONE_EXPERT_RECOMMENDED";
this.CAMPAIGN_ONE_PARTICIPANT_RECOMMENDED = "MSG_CAMPAIGN_ONE_PARTICIPANT_RECOMMENDED";

this.CAMPAIGN_VALIDITY = "MSG_CAMPAIGN_VALIDITY";
this.CAMPAIGN_VALIDITY_PAST = "MSG_CAMPAIGN_VALIDITY_PAST";
this.CAMPAIGN_SUBMIT_PERIOD = "MSG_CAMPAIGN_SUBMIT_PERIOD";
this.CAMPAIGN_SUBMIT_PERIOD_PAST = "MSG_CAMPAIGN_SUBMIT_PERIOD_PAST";

this.CAMPAIGN_DELETE_NOT_EMPTY = "MSG_CAMPAIGN_DELETE_NOT_EMPTY";

this.CAMPAIGN_ONE_PHASE_MANDATORY = "MSG_CAMPAIGN_ONE_PHASE_MANDATORY";

this.CAMPAIGN_INVALID_COLOR_CODE = "MSG_CAMPAIGN_INVALID_COLOR_CODE";
this.CAMPAIGN_INVALID_VOTE_TYPE = "MSG_CAMPAIGN_INVALID_VOTE_TYPE";
this.CAMPAIGN_INVALID_PHASE_CODE = "MSG_CAMPAIGN_INVALID_PHASE_CODE";
this.CAMPAIGN_INVALID_STATUS_MODEL_CODE = "MSG_CAMPAIGN_INVALID_STATUS_MODEL_CODE";
this.CAMPAIGN_INVALID_LIMITATION_ACTION_CODE = "MS_CAMPAIGN_INVALID_ACTION_CODE";

this.CAMPAIGN_ONLY_PUBLISH = "MSG_CAMPAIGN_ONLY_PUBLISH";

this.CAMPAIGN_PUBLISH_PHASE_ERR = "MSG_CAMPAIGN_PUBLISH_PHASE_ERR";
this.CAMPAIGN_PUBLISH_VOTE_ERR = "MSG_CAMPAIGN_PUBLISH_VOTE_ERR";
this.CAMPAIGN_VOTE_STAR_NO_MISSING = "MSG_CAMPAIGN_VOTE_MISSING_STAR_NO";
this.CAMPAIGN_VOTE_REASON_LIST_MISSING = "MSG_CAMPAIGN_VOTE_MISSING_REASON_LIST";
this.CAMPAIGN_VOTE_EMPTY_REASON_LIST = "MSG_CAMPAIGN_VOTE_EMPTY_REASON_LIST";
this.CAMPAIGN_VOTE_TYPE_UNCHANGEABLE = "MSG_CAMPAIGN_VOTE_TYPE_UNCHANGEABLE";
this.CAMPAIGN_PUBLISH_TITLE_IMAGE_ERR = "MSG_CAMPAIGN_PUBLISH_TITLE_IMAGE_ERR";
this.CAMPAIGN_PUBLISH_PHASE_DELETE_ERR = "MSG_CAMPAIGN_PUBLISH_PHASE_DELETE_ERR";
this.CAMPAIGN_PUBLISH_PHASE_CHANGE_ERR = "MSG_CAMPAIGN_PUBLISH_PHASE_CHANGE_ERR";

this.CAMPAIGN_VOTE_BY_GROUP_ERROR = "MSG_CAMPAIGN_VOTE_BY_GROUP_ERROR";

this.CAMPAIGN_PAGE_INCOMPLETE_TITLE = "MSG_CAMPAIGN_PAGE_INCOMPLETE_TITLE";
this.CAMPAIGN_PAGE_INCOMPLETE_CONTENT = "MSG_CAMPAIGN_PAGE_INCOMPLETE_CONTENT";
this.CAMPAIGN_PAGE_DUPLICATION = "MSG_CAMPAIGN_PAGE_DUPLICATION";

this.CAMPAIGN_DUPLICATE_PHASE_SEQUENCE ="MSG_CAMPAIGN_DUPLICATE_PHASE_SEQUENCE";
this.CAMPAIGN_PHASE_DUPLICATION = "MSG_CAMPAIGN_PHASE_DUPLICATION";
this.CAMPAIGN_PHASE_SEQUENCE_INVALID = "MSG_CAMPAIGN_PHASE_SEQUENCE_INVALID";

this.PHASE_INVALID_CODE = "MSG_PHASE_INVALID_CODE";
this.PHASE_DUPLICATE_CODE = "MSG_PHASE_DUPLICATE_CODE";
this.PHASE_INVALID_VALUE = "MSG_PHASE_INVALID_VALUE";
this.PHASE_DUPLICATE_VALUE = "MSG_PHASE_DUPLICATE_VALUE";
this.PHASE_UNCHANGEABLE = "MSG_PHASE_UNCHANGEABLE";

this.CAMPAIGN_PUBLISH_LIMIT="MSG_PUBLISH_LIMIT";

this.CAMPAIGN_ADVANCE_CHANGE_VOTING_DELETE = "MSG_CAMPAIGN_ADVANCE_CHANGE_VOTING_DELETE";
this.CAMPAIGN_ADVANCE_CHANGE_PHASE_CODE_CHANGE = "MSG_CAMPAIGN_ADVANCE_CHANGE_PHASE_CODE_CHANGE";
this.CAMPAIGN_ADVANCE_CHANGE_STATUS_MODEL_CODE_CHANGE = "MSG_CAMPAIGN_ADVANCE_CHANGE_STATUS_MODEL_CODE_CHANGE";
this.CAMPAIGN_ADVANCE_CHANGE_PHASE_DELETE = "MSG_CAMPAIGN_ADVANCE_CHANGE_PHASE_DELETE";
this.CAMPAIGN_ADVANCE_CHANGE_ONLY_PUBLISHED = "MSG_CAMPAIGN_ADVANCE_CHANGE_ONLY_PUBLISHED";
this.CAMPAIGN_ADVANCE_CHANGE_PARAMETER_REQUIRED = "MSG_CAMPAIGN_ADVANCE_CHANGE_PARAMETER_REQUIRED";
this.CAMPAIGN_ADVANCE_CHANGE_PHASE_NOT_FOUND = "MSG_CAMPAIGN_ADVANCE_CHANGE_PHASE_NOT_FOUND";

this.VOTE_ACTIVATION_INVALID_STAR_VOTE = "MSG_VOTE_ACTIVATION_INVALID_STAR_VOTE";
this.VOTE_ACTIVATION_INVALID_VOTE_SCORE = "MSG_VOTE_ACTIVATION_INVALID_VOTE_SCORE";

this.CAMP_RESP_LIST_UNCHANGABLE = "MSG_CAMP_RESP_LIST_UNCHANGABLE";
this.CAMP_ANONYMOUS_FUNCTION_UNCHANGEABLE = "MSG_CAMP_ANONYMOUS_FUNCTION_UNCHANGEABLE";
this.CAMP_ANONYMOUS_DUPLICATION = "MSG_CAMP_ANONYMOUS_DUPLICATION";

this.CAMPAIGN_REGISTER_SUBMIT_FROM_MANDATORY = "MSG_CAMPAIGN_REGISTER_SUBMIT_FROM_MANDATORY";
this.CAMPAIGN_REGISTER_TO_MANDATORY = "MSG_CAMPAIGN_REGISTER_TO_MANDATORY";
this.CAMPAIGN_SUBMIT_TO_MANDATORY = "MSG_CAMPAIGN_SUBMIT_TO_MANDATORY";
this.CAMPAIGN_REGISTER_PERIOD = "MSG_CAMPAIGN_REGISTER_PERIOD";

this.CAMPAIGN_REGISTER_APPLY_ERROR = "MSG_CAMPAIGN_REGISTER_APPLY_ERROR";
this.CAMPAIGN_REGISTER_APPLY_REASON_ERROR = "MSG_CAMPAIGN_REGISTER_APPLY_REASON_ERROR";

this.CAMPAIGN_REWARD_ACTIVE_ALLOWED_MANDATORY = "MSG_CAMPAIGN_REWARD_ACTIVE_ALLOWED_MANDATORY";
this.CAMPAIGN_ONE_REWARD_PHASE_MANDATORY = "MSG_CAMPAIGN_ONE_REWARD_PHASE_MANDATORY";

this.TASK_INVALID_DATE = "MSG_TASK_INVALID_DATE";
this.CAMPAIGN_TASK_INVALID_DATE = "MSG_CAMPAIGN_TASK_INVALID_DATE";
this.CAMPAIGN_MILESTONE_INVALID_DATE = "MSG_CAMPAIGN_MILESTONE_INVALID_DATE";
this.CAMPAIGN_TASK_INVALID_COUNT = "MSG_CAMPAIGN_TASK_INVALID_COUNT";
this.CAMPAIGN_MILESTONE_INVALID_COUNT = "MSG_CAMPAIGN_MILESTONE_INVALID_COUNT";
this.CAMPAIGN_TASK_MILESTONE_INVALID_COUNT = "MSG_CAMPAIGN_TASK_MILESTONE_INVALID_COUNT";
this.CAMPAIGN_MILESTONE_NAME_MISSING = "MSG_CAMPAIGN_MILESTONE_NAME_MISSING";

this.CAMPAIGN_INTEGRATION_LAYOUT_FIELD_NULL = "MSG_CAMPAIGN_INTEGRATION_LAYOUT_FIELD_NULL";
this.CAMPAIGN_INTEGRATION_LAYOUT_FIELD_BLANK = "MSG_CAMPAIGN_INTEGRATION_LAYOUT_FIELD_BLANK";
this.CAMPAIGN_DUPLICATE_VANITY_CODE = "MSG_CAMPAIGN_DUPLICATE_VANITY_CODE";
this.CAMPAIGN_INVALID_VANITY_CODE = "MSG_CAMPAIGN_INVALID_VANITY_CODE";