this.AUTH_MISSING_WALL_WRITE = "MSG_AUTH_MISSING_WALL_WRITE";
this.AUTH_MISSING_WALL_ADMIN = "MSG_AUTH_MISSING_WALL_ADMIN";
this.AUTH_MISSING_WALL_READ = "MSG_AUTH_MISSING_WALL_READ";

this.WALL_INVALID_BACKGROUND_COLOR = "MSG_WALL_INVALID_BACKGROUND_COLOR";
this.WALL_INVALID_BACKGROUND_SIZE = "MSG_WALL_INVALID_BACKGROUND_SIZE";
this.WALL_INVALID_BACKGROUND_POS = "MSG_WALL_INVALID_BACKGROUND_POS";
this.WALL_INVALID_BACKGROUND_ZOOM = "MSG_WALL_INVALID_BACKGROUND_ZOOM";
this.WALL_AMBIGUOUS_BACKGROUND_CHANGES = "MSG_AMBIGUOUS_BACKGROUND_CHANGES";

this.WALL_ITEM_INVALID_CONTENT = "MSG_WALL_ITEM_INVALID_CONTENT";
this.WALL_ITEM_INVALID_CONTENT_FIELD = "MSG_WALL_ITEM_INVALID_CONTENT_FIELD";
this.WALL_ITEM_MISSING_CONTENT_FIELD = "MSG_WALL_ITEM_MISSING_CONTENT_FIELD";
this.WALL_ITEM_INVALID_CONTENT_FIELD_TYPE = "MSG_WALL_ITEM_INVALID_CONTENT_FIELD_TYPE";
this.WALL_ITEM_INVALID_ENUM_VALUE = "MSG_WALL_ITEM_INVALID_ENUM_VALUE";
this.WALL_ITEM_INVALID_COLOR = "MSG_WALL_ITEM_INVALID_COLOR";
this.WALL_ITEM_INVALID_SIZE = "MSG_WALL_ITEM_INVALID_SIZE";

this.WALL_ITEM_INVALID_IMAGE_ASSIGNMENT = "MSG_WALL_ITEM_INVALID_IMAGE_ASSIGNMENT";
this.WALL_ITEM_INVALID_ATTACHMENT_ASSIGNMENT = "MSG_WALL_ITEM_INVALID_ATTACHMENT_ASSIGNMENT";

this.WALL_DUPLICATE_ASSIGNMENT = "MSG_WALL_DUPLICATE_ASSIGNMENT";
this.WALL_DUPLICATE_ROLE_TYPE = "MSG_WALL_DUPLICATE_ROLE_TYPE";
this.WALL_ASSIGNED_CANNOT_BE_UNLOCKED = "MSG_WALL_ASSIGNED_CANNOT_BE_UNLOCKED";

this.WALL_NON_DISTINCT_USER_PERMISSION = "MSG_WALL_NON_DISTINCT_USER_PERMISSION";
this.WALL_NO_WALL_SESSION = "MSG_WALL_NO_WALL_SESSION";
this.WALL_IS_LOCKED = "MSG_WALL_IS_LOCKED";