this.AUTH_MISSING_FOLLOW_UP_CREATE = "MSG_AUTH_MISSING_FOLLOW_UP_CREATE";
this.AUTH_MISSING_FOLLOW_UP_UPDATE = "MSG_AUTH_MISSING_FOLLOW_UP_UPDATE";
this.AUTH_MISSING_FOLLOW_UP_DELETE = "MSG_AUTH_MISSING_FOLLOW_UP_DELETE";
this.AUTH_MISSING_FOLLOW_UP_READ   = "MSG_AUTH_MISSING_FOLLOW_UP_READ";

this.DUPLICATE_FOLLOW_UP = "MSG_DUPLICATE_FOLLOW_UP";
this.FOLLOW_UP_OBJECT_TYPE_UNCHANGEABLE = "MSG_FOLLOW_UP_OBJECT_TYPE_UNCHANGEABLE";
this.FOLLOW_UP_OBJECT_ID_UNCHANGEABLE = "MSG_FOLLOW_UP_OBJECT_ID_UNCHANGEABLE";
this.FOLLOW_UP_FOLLOW_UP_NOT_POSSIBLE = "MSG_FOLLOW_UP_FOLLOW_UP_NOT_POSSIBLE";
this.FOLLOW_UP_FOLLOW_DATE_GE_TODAY = "MSG_FOLLOW_UP_FOLLOW_DATE_GE_TODAY";
