this.AUTH_MISSING_REPORT_DELETE = "MSG_REPORT_AUTH_MISSING_DELETE";
this.AUTH_MISSING_REPORT_UPDATE = "MSG_REPORT_AUTH_MISSING_UPDATE";
this.REPORT_CONFIG_INVALID = "MSG_REPORT_CONFIG_INVALID";
this.REPORT_DUPLICATE_CODE = "MSG_REPORT_DUPLICATE_CODE";